
theme = "my-theme" # お好みのテーマ（catppuccin, draculaなど）

[editor]
bufferline = "multiple"  # 複数バッファ時に上部に一覧表示
line-number = "relative" # 行番号を相対表示に（移動が楽になります）
cursorline = true        # 現在の行をハイライト
auto-format = true       # 保存時に自動フォーマット
idle-timeout = 200       # オートコンプリートなどの反応速度（ミリ秒）
color-modes = true       # モード（Normal/Insert）によって色を変える
true-color = true        # 24bitカラーを有効化
undercurl = true                      # ターミナルが対応していればアンダーカールを使用

clipboard-provider = "x-clip"
[editor.lsp]
display-inlay-hints = true
[editor.cursor-shape]
insert = "bar"           # インサートモード時は棒状のカーソル
normal = "block"         # ノーマルモード時はブロック
select = "underline"     # 選択モード時は下線

[editor.file-picker]
hidden = true            # ドットファイルも検索対象にする

[editor.statusline]
left = [
  "mode",
  "file-type",
  "separator",
  "file-name",
  "file-modification-indicator",
  "read-only-indicator",
  "separator",
]

right = [
  "version-control",
  "separator",
  "diagnostics",
  "separator",
  "position",
  "position-percentage",]

# 非塗りつぶし（Neovim実用派）
separator = " "
#
mode.normal = " NORMAL "
mode.insert = " INSERT "
mode.select = " SELECT "

diagnostics = ["error", "warning", "info", "hint"]
[editor.inline-diagnostics]
cursor-line = "warning"   # カーソル行のみ warning 以上をインライン表示（赤/黄）
other-lines = "disable"   # 他行はノイズ防止で非表示（info/hintは行末で青）

[editor.indent-guides]
render = true            # インデントの縦線を表示
character = "╎"          # 縦線の文字

[keys.normal]
# Escキーを押しやすく（好みに合わせて）
esc = ["collapse_selection", "keep_primary_selection"]
# スペース + w で保存
"y" = ":clipboard-yank"
"p" = ":clipboard-paste-after"
"P" = ":clipboard-paste-before"
"space" = {"q" = ":quit",o = "file_picker_in_current_buffer_directory" }
A-w = ":buffer-close"

C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ':set mouse false',
  ':set mouse true',
]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"H" = ["goto_line_start"]
"L" = ["goto_line_end"]
# 行選択の改善
A-x = "extend_to_line_bounds"
X = "select_line_above"

"+" = { w = ":toggle whitespace.render all", s = ":toggle soft-wrap.enable", f = ":format" }

tab = ":buffer-next"
S-tab = ":buffer-previous"
[keys.select]
"y" = ":clipboard-yank"
"p" = ":clipboard-paste-after"
"P" = ":clipboard-paste-before"
"H" = ["goto_line_start"]
"L" = ["goto_line_end"]
# 行選択の改善
A-x = "extend_to_line_bounds"
X = "select_line_above"
[keys.insert]
j = { k = "normal_mode" }
[editor.auto-save]
focus-lost = true
after-delay.enable = true
